version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: kiosk
      MYSQL_DATABASE: kiosk
#      TZ: Asia/Seoul
    ports:
      - 3306:3306