spring:
  datasource:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    initialization-mode: always

    hikari:
      maximum-pool-size: 4
    username: root
    password: kiosk
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kiosk


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

