spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    username: kiosk
    password: kioskpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kiosk.cjoe7kvjgtot.ap-northeast-2.rds.amazonaws.com:3306/kiosk

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true